graph TD
  A[Schedule Trigger] --> B[Config]
  B --> C[Format Channel Handles]
  C --> D[Get Channel IDs]
  D --> E[Split Out Channels]
  E --> F[Get Channels Videos]
  F --> G[Loop Over Videos]
  G --> H[Aggregate]
  H --> I[Enrich Additional Video Metadata]
  I --> J[Split Out Videos]
  J --> K[Enrich With Additional Metadata]
  K --> L[Code]
  L --> M[Convert to File]
  M --> N[Read/Write Files from Disk]
  N --> O[Upload file]
  L --> P[Insert or update rows]
  L --> Q[Append or update row]
  style O fill:#f9f,stroke:#333,stroke-width:2px
  style P fill:#f9f,stroke:#333,stroke-width:2px
  style Q fill:#f9f,stroke:#333,stroke-width:2px